import { useEffect, useMemo, useRef, useState } from "react";
import {
  coachReply, buildCoachMessages, isOnTopic, isAnalysisQuestion, OFFTOPIC_REPLY,
  COACH_STARTER_CHIPS, type CoachCtx, type ChatMsg,
} from "./respond";
import {
  webgpuAvailable, llmOptedIn, setLlmOptIn, loadCoachLLM, resetCoachLLM, streamCoachLLM,
  savedModelKey, setSavedModelKey, LLM_MODELS, LLM_MODEL_KEYS,
  type LLMPhase, type LLMModelKey,
} from "./llm";
import { Markdown } from "./Markdown";
import type { HistoryEntry } from "../engine/history";
import type { MLCEngineInterface } from "@mlc-ai/web-llm";

type Msg = {
  role: "user" | "coach";
  text: string;
  ts: number;
  ai?: boolean;    // generated by the LLM
  pick?: boolean;  // render the analysis-picker under this message
  meta?: boolean;  // housekeeping line — excluded from LLM conversation history
};

const now = () => Date.now();
const hhmm = (t: number) => new Date(t).toLocaleTimeString("tr-TR", { hour: "2-digit", minute: "2-digit" });

const GREETING =
  "Merhaba! 🎾 Ben VuruşKoç AI. Tenis tekniğin, antrenmanın ve vuruş analizlerin hakkında " +
  "konuşabiliriz — tenis dışı konularda yardımcı olamam.";
const PICK_PROMPT = "Hangi analizi konuşalım? Genel tenis soruları için “Analiz olmadan”ı seç.";

const CHIP_ICON: Record<string, string> = {
  "Son analizimi anlat": "📊",
  "Neye çalışmalıyım?": "🎯",
  "20 dakikalık antrenman hazırla": "⚡",
  "Evde raketsiz ne yapabilirim?": "🏠",
  "Evde ne yapabilirim?": "🏠",
  "İlerlemem nasıl?": "📈",
};

const strokeTR = (s: string) => (s === "serve" ? "servis" : s === "backhand" ? "backhand" : "forehand");
function entryLabel(e: HistoryEntry): string {
  const d = new Date(e.created_at).toLocaleDateString("tr-TR", { day: "numeric", month: "short" });
  const sc = e.result.swing_score != null ? `${Math.round(e.result.swing_score)}` : "–";
  return `${d} · ${strokeTR(e.result.stroke)} · ${sc}/100`;
}

const Mark = () => (
  <span className="cav" aria-hidden>
    <svg width="15" height="15" viewBox="0 0 64 64" fill="none">
      <path d="M14 46 L30 22 L30 38 L50 14" stroke="#12200a" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  </span>
);
const SendIcon = () => (
  <svg viewBox="0 0 24 24" width="17" height="17" aria-hidden><path d="M3.4 20.4 21 12 3.4 3.6 3 10l12 2-12 2z" fill="currentColor" /></svg>
);

/** plain multi-line render for user + housekeeping lines (no markdown) */
function Plain({ text }: { text: string }) {
  return <>{text.split("\n").map((ln, j) => <div key={j}>{ln || " "}</div>)}</>;
}

export function Coach({ history, activeId }: { history: HistoryEntry[]; activeId?: string | null }) {
  const [selId, setSelId] = useState<string>("");
  const [ctxChosen, setCtxChosen] = useState<boolean>(() => !!activeId);
  const [pendingQ, setPendingQ] = useState<string | null>(null);
  const [msgs, setMsgs] = useState<Msg[]>([{ role: "coach", text: GREETING, ts: now() }]);
  const [chips, setChips] = useState<string[]>(COACH_STARTER_CHIPS);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);

  const [phase, setPhase] = useState<LLMPhase>("idle");
  const [modelKey, setModelKey] = useState<LLMModelKey>(() => savedModelKey());
  const [loadedKey, setLoadedKey] = useState<LLMModelKey>(() => savedModelKey());
  const [progress, setProgress] = useState<{ pct: number; text: string }>({ pct: 0, text: "" });
  const [expanded, setExpanded] = useState(false);
  const engineRef = useRef<MLCEngineInterface | null>(null);

  const selEntry = useMemo(() => history.find((e) => e.id === selId) ?? null, [history, selId]);

  // when a result is opened elsewhere, adopt it as the context (once). Otherwise
  // never auto-pick — the coach asks in the chat and the user chooses there.
  const lastActive = useRef<string | null>(null);
  useEffect(() => {
    if (activeId && activeId !== lastActive.current && history.some((e) => e.id === activeId)) {
      lastActive.current = activeId;
      setSelId(activeId);
      setCtxChosen(true);
      return;
    }
    lastActive.current = activeId ?? null;
    setSelId((cur) => (cur && history.some((e) => e.id === cur) ? cur : ""));
  }, [activeId, history]);

  // first thing the coach does: ask which analysis (if there is one)
  useEffect(() => {
    if (activeId || ctxChosen || history.length === 0) return;
    setMsgs((m) => (m.length === 1 ? [...m, { role: "coach", text: PICK_PROMPT, ts: now(), pick: true, meta: true }] : m));
  }, [history.length, activeId, ctxChosen]);

  useEffect(() => { endRef.current?.scrollIntoView({ block: "nearest" }); }, [msgs]);

  useEffect(() => {
    if (!expanded) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setExpanded(false); };
    window.addEventListener("keydown", onKey);
    return () => { document.body.style.overflow = prev; window.removeEventListener("keydown", onKey); };
  }, [expanded]);

  useEffect(() => {
    if (!webgpuAvailable()) { setPhase("unsupported"); return; }
    if (llmOptedIn()) void startLLM(savedModelKey());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function startLLM(key: LLMModelKey) {
    setModelKey(key);
    setSavedModelKey(key);
    setPhase("loading");
    setProgress({ pct: 0, text: "başlatılıyor…" });
    try {
      const engine = await loadCoachLLM(key, (p) => {
        setProgress({ pct: Math.round((p.progress ?? 0) * 100), text: p.text || "" });
      });
      engineRef.current = engine;
      setLoadedKey(key);
      setLlmOptIn(true);
      setPhase("ready");
    } catch (e) {
      console.error("[coach] LLM load failed", e);
      setPhase("error");
    }
  }

  async function changeModel() {
    engineRef.current = null;
    await resetCoachLLM();
    setPhase("idle");
  }
  function disableLLM() {
    setLlmOptIn(false);
    engineRef.current = null;
    void resetCoachLLM();
    setPhase(webgpuAvailable() ? "idle" : "unsupported");
  }

  async function runAnswer(t: string, ctx: CoachCtx, snapshot: Msg[]) {
    const followUp = snapshot.filter((m) => !m.meta).length > 1;

    if (phase === "ready" && engineRef.current) {
      setBusy(true);
      setMsgs((m) => [...m, { role: "coach", text: "", ts: now(), ai: true }]);
      try {
        const turns: ChatMsg[] = snapshot
          .slice(1)
          .filter((m) => m.text.trim() && !m.meta)
          .map((m) => ({ role: m.role === "user" ? "user" : "assistant", content: m.text }));
        let acc = "";
        for await (const tok of streamCoachLLM(engineRef.current, buildCoachMessages(t, ctx, turns) as any)) {
          acc += tok;
          setMsgs((m) => {
            const n = m.slice();
            n[n.length - 1] = { ...n[n.length - 1], text: acc };
            return n;
          });
        }
        if (!acc.trim()) throw new Error("empty");
      } catch (e) {
        console.error("[coach] generation failed, falling back", e);
        const ans = coachReply(t, ctx, { followUp });
        setMsgs((m) => {
          const n = m.slice();
          n[n.length - 1] = { ...n[n.length - 1], text: ans.text, ai: false };
          return n;
        });
        setChips(ans.chips ?? COACH_STARTER_CHIPS);
      } finally {
        setBusy(false);
      }
      return;
    }

    const ans = coachReply(t, ctx, { followUp });
    setMsgs((m) => [...m, { role: "coach", text: ans.text, ts: now() }]);
    setChips(ans.chips ?? COACH_STARTER_CHIPS);
  }

  function pick(id: string) {
    setSelId(id);
    setCtxChosen(true);
    const e = history.find((x) => x.id === id) ?? null;
    const conf = e
      ? `Tamam — ${entryLabel(e)} analizi üzerinden konuşuyoruz.`
      : "Tamam, belirli bir analize bağlı kalmadan devam edelim.";
    setMsgs((m) => [...m, { role: "coach", text: conf, ts: now(), meta: true }]);
    const q = pendingQ;
    setPendingQ(null);
    if (!q) return;
    let cut = msgs.length;
    for (let i = msgs.length - 1; i >= 0; i--) {
      if (msgs[i].role === "user" && msgs[i].text === q) { cut = i; break; }
    }
    void runAnswer(q, { result: e?.result ?? null, history }, msgs.slice(0, cut));
  }

  function showPicker() {
    setMsgs((m) => [...m, { role: "coach", text: PICK_PROMPT, ts: now(), pick: true, meta: true }]);
  }

  async function ask(text: string) {
    const t = text.trim();
    if (!t || busy) return;
    const snapshot = msgs;
    setInput("");
    setMsgs((m) => [...m, { role: "user", text: t, ts: now() }]);

    const ctx: CoachCtx = { result: selEntry?.result ?? null, history };
    const followUp = snapshot.filter((m) => !m.meta).length > 1;

    if (!isOnTopic(t, ctx, followUp)) {
      setMsgs((m) => [...m, { role: "coach", text: OFFTOPIC_REPLY, ts: now() }]);
      setChips(COACH_STARTER_CHIPS);
      return;
    }
    if (isAnalysisQuestion(t) && !selId && !ctxChosen && history.length > 0) {
      setPendingQ(t);
      setMsgs((m) => [...m, { role: "coach", text: PICK_PROMPT, ts: now(), pick: true, meta: true }]);
      return;
    }
    await runAnswer(t, ctx, snapshot);
  }

  const headSub =
    phase === "ready" ? `model: ${LLM_MODELS[loadedKey].sub} · cihazında`
    : phase === "loading" ? `${LLM_MODELS[modelKey].sub} indiriliyor — %${progress.pct}`
    : phase === "unsupported" ? "kural tabanlı koç · cihazında"
    : "kişisel tenis koçun · cihazında çalışır";
  const offer = LLM_MODELS[modelKey];

  return (
   <>
    {expanded && <div className="coach-backdrop" onClick={() => setExpanded(false)} />}
    <div className={"card coach" + (expanded ? " coach--expanded" : "")}>
      <div className="coach-head">
        <span className="cav big" aria-hidden>
          <svg width="18" height="18" viewBox="0 0 64 64" fill="none">
            <path d="M14 46 L30 22 L30 38 L50 14" stroke="#12200a" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </span>
        <div className="coach-head-t">
          <div className="coach-title">VuruşKoç AI <span className="coach-beta">beta</span></div>
          <div className="coach-sub">{headSub}</div>
        </div>
        <div className="coach-head-act">
          <button type="button" className="coach-ic" title={expanded ? "Küçült" : "Tam ekran"}
            aria-label={expanded ? "Küçült" : "Tam ekran"} onClick={() => setExpanded((v) => !v)}>
            {expanded ? "–" : "⤢"}
          </button>
          {expanded && (
            <button type="button" className="coach-ic" title="Kapat" aria-label="Kapat"
              onClick={() => setExpanded(false)}>✕</button>
          )}
        </div>
      </div>

      <div className="coach-ctx-line">
        <span>Bağlam: <b>{selEntry ? entryLabel(selEntry) : "genel"}</b></span>
        {history.length > 0 && (
          <button type="button" className="linklike" onClick={showPicker} disabled={busy}>değiştir</button>
        )}
      </div>

      {phase === "idle" && (
        <div className="coach-llm-offer">
          <div className="cllo-body">
            <b>⚡ Gelişmiş yapay zekâ (deneysel)</b>
            <span>Model tamamen cihazında çalışır; indikten sonra internet gerekmez.</span>
            <div className="cllo-tiers" role="radiogroup" aria-label="Model">
              {LLM_MODEL_KEYS.map((k) => (
                <button key={k} className={"cllo-tier" + (modelKey === k ? " on" : "")}
                  aria-pressed={modelKey === k} onClick={() => setModelKey(k)}>
                  <b>{LLM_MODELS[k].label}</b>
                  <i>{LLM_MODELS[k].sub}</i>
                  <em>~{(LLM_MODELS[k].downloadMB / 1000).toFixed(LLM_MODELS[k].downloadMB < 1000 ? 2 : 1)} GB</em>
                </button>
              ))}
            </div>
            <span className="cllo-note">{offer.note}</span>
          </div>
          <button className="btn sm" onClick={() => void startLLM(modelKey)}>İndir & etkinleştir</button>
        </div>
      )}
      {phase === "loading" && (
        <div className="coach-llm-load">
          <div className="cll-bar"><span style={{ width: `${progress.pct}%` }} /></div>
          <span className="cll-txt">{progress.pct}% · {progress.text || "hazırlanıyor…"}</span>
        </div>
      )}
      {phase === "error" && (
        <div className="coach-llm-load err">
          Model yüklenemedi (bellek yetmemiş olabilir — daha küçük bir model dene).{" "}
          <button className="linklike" onClick={() => void changeModel()}>model seç</button>
        </div>
      )}

      <div className="coach-log">
        {msgs.map((m, i) => (
          <div key={i} className={"cmsg " + m.role + (m.meta ? " meta" : "")}>
            {m.role === "coach" && !m.meta && <Mark />}
            <div className="cmsg-col">
              <div className="cbubble">
                {m.text === "" ? <span className="ctyping"><i /><i /><i /></span>
                  : m.role === "coach" && !m.meta ? <Markdown text={m.text} />
                  : <Plain text={m.text} />}
              </div>
              {!m.meta && m.text !== "" && <span className="cmsg-time">{hhmm(m.ts)}</span>}
              {m.pick && (
                <div className="coach-pick">
                  {history.map((e) => (
                    <button key={e.id} className="chip" onClick={() => pick(e.id)} disabled={busy}>
                      {entryLabel(e)}
                    </button>
                  ))}
                  <button className="chip ghost" onClick={() => pick("")} disabled={busy}>Analiz olmadan</button>
                </div>
              )}
            </div>
          </div>
        ))}
        <div ref={endRef} />
      </div>

      <div className="coach-chips">
        {chips.map((c) => (
          <button key={c} className="chip" onClick={() => void ask(c)} disabled={busy}>
            {CHIP_ICON[c] ? <span className="chip-ic">{CHIP_ICON[c]}</span> : null}{c}
          </button>
        ))}
      </div>

      <form className="coach-input" onSubmit={(e) => { e.preventDefault(); void ask(input); }}>
        <input value={input} onChange={(e) => setInput(e.target.value)}
          placeholder={busy ? "koç yazıyor…" : "Tenisle ilgili bir şey sor…"} disabled={busy} />
        <button className="coach-send" type="submit" disabled={!input.trim() || busy} aria-label="Gönder">
          <SendIcon />
        </button>
      </form>

      <div className="coach-status">
        <span className={"cst-dot" + (phase === "ready" ? " on" : phase === "loading" ? " busy" : "")} />
        <span>
          {phase === "ready" ? `AI çevrimiçi · ${LLM_MODELS[loadedKey].sub} · veri cihazında`
            : phase === "loading" ? "model indiriliyor…"
            : phase === "unsupported" ? "kural tabanlı motor (WebGPU yok)"
            : "kural tabanlı motor · sunucuya veri gitmez"}
        </span>
        {phase === "ready" && (
          <span className="cst-links">
            <button className="linklike" onClick={() => void changeModel()}>model</button>
            <button className="linklike" onClick={disableLLM}>kapat</button>
          </span>
        )}
      </div>
    </div>
   </>
  );
}
