import { useEffect, useMemo, useRef, useState } from "react";
import {
  coachReply, buildCoachMessages, isOnTopic, isAnalysisQuestion, OFFTOPIC_REPLY,
  COACH_STARTER_CHIPS, type CoachCtx, type ChatMsg,
} from "./respond";
import {
  webgpuAvailable, llmOptedIn, setLlmOptIn, loadCoachLLM, resetCoachLLM, streamCoachLLM,
  savedModelKey, setSavedModelKey, LLM_MODELS, LLM_MODEL_KEYS,
  type LLMPhase, type LLMModelKey,
} from "./llm";
import type { HistoryEntry } from "../engine/history";
import type { MLCEngineInterface } from "@mlc-ai/web-llm";

type Msg = {
  role: "user" | "coach";
  text: string;
  ai?: boolean;    // generated by the LLM
  pick?: boolean;  // render the analysis-picker under this message
  meta?: boolean;  // housekeeping line — excluded from LLM conversation history
};

const GREETING =
  "Merhaba, ben senin tenis koçunum. Tekniğin, antrenmanın ve vuruş analizlerin hakkında " +
  "konuşabiliriz. (Tenis dışı sorulara yanıt veremem.)";
const PICK_PROMPT = "Hangi analizi konuşalım? Genel tenis soruları için “Analiz olmadan”ı seç.";

const strokeTR = (s: string) => (s === "serve" ? "servis" : s === "backhand" ? "backhand" : "forehand");
function entryLabel(e: HistoryEntry): string {
  const d = new Date(e.created_at).toLocaleDateString("tr-TR", { day: "numeric", month: "short" });
  const sc = e.result.swing_score != null ? `${Math.round(e.result.swing_score)}` : "–";
  return `${d} · ${strokeTR(e.result.stroke)} · ${sc}/100`;
}

function Lines({ text }: { text: string }) {
  return (
    <>
      {text.split("\n").map((ln, j) =>
        ln.startsWith("• ") ? <div key={j} className="cbul">{ln.slice(2)}</div>
        : /^\s{2,}•\s/.test(ln) ? <div key={j} className="cbul cbul-sub">{ln.replace(/^\s+•\s/, "")}</div>
        : ln.trim() === "" ? <div key={j} className="cgap" />
        : <div key={j}>{ln}</div>
      )}
    </>
  );
}

export function Coach({ history, activeId }: { history: HistoryEntry[]; activeId?: string | null }) {
  const [selId, setSelId] = useState<string>("");
  const [ctxChosen, setCtxChosen] = useState<boolean>(() => !!activeId);
  const [pendingQ, setPendingQ] = useState<string | null>(null);
  const [msgs, setMsgs] = useState<Msg[]>([{ role: "coach", text: GREETING }]);
  const [chips, setChips] = useState<string[]>(COACH_STARTER_CHIPS);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);

  const [phase, setPhase] = useState<LLMPhase>("idle");
  const [modelKey, setModelKey] = useState<LLMModelKey>(() => savedModelKey());
  const [loadedKey, setLoadedKey] = useState<LLMModelKey>(() => savedModelKey());
  const [progress, setProgress] = useState<{ pct: number; text: string }>({ pct: 0, text: "" });
  const engineRef = useRef<MLCEngineInterface | null>(null);

  const selEntry = useMemo(() => history.find((e) => e.id === selId) ?? null, [history, selId]);

  // when a result is opened elsewhere, adopt it as the context (once). Otherwise
  // never auto-pick — the coach asks in the chat and the user chooses there.
  const lastActive = useRef<string | null>(null);
  useEffect(() => {
    if (activeId && activeId !== lastActive.current && history.some((e) => e.id === activeId)) {
      lastActive.current = activeId;
      setSelId(activeId);
      setCtxChosen(true);
      return;
    }
    lastActive.current = activeId ?? null;
    setSelId((cur) => (cur && history.some((e) => e.id === cur) ? cur : ""));
  }, [activeId, history]);

  // the very first thing the coach does: ask which analysis (if there is one)
  useEffect(() => {
    if (activeId || ctxChosen || history.length === 0) return;
    setMsgs((m) => (m.length === 1 ? [...m, { role: "coach", text: PICK_PROMPT, pick: true, meta: true }] : m));
  }, [history.length, activeId, ctxChosen]);

  useEffect(() => { endRef.current?.scrollIntoView({ block: "nearest" }); }, [msgs]);

  useEffect(() => {
    if (!webgpuAvailable()) { setPhase("unsupported"); return; }
    if (llmOptedIn()) void startLLM(savedModelKey());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function startLLM(key: LLMModelKey) {
    setModelKey(key);
    setSavedModelKey(key);
    setPhase("loading");
    setProgress({ pct: 0, text: "başlatılıyor…" });
    try {
      const engine = await loadCoachLLM(key, (p) => {
        setProgress({ pct: Math.round((p.progress ?? 0) * 100), text: p.text || "" });
      });
      engineRef.current = engine;
      setLoadedKey(key);
      setLlmOptIn(true);
      setPhase("ready");
    } catch (e) {
      console.error("[coach] LLM load failed", e);
      setPhase("error");
    }
  }

  async function changeModel() {
    engineRef.current = null;
    await resetCoachLLM();
    setPhase("idle");
  }
  function disableLLM() {
    setLlmOptIn(false);
    engineRef.current = null;
    void resetCoachLLM();
    setPhase(webgpuAvailable() ? "idle" : "unsupported");
  }

  async function runAnswer(t: string, ctx: CoachCtx, snapshot: Msg[]) {
    const followUp = snapshot.filter((m) => !m.meta).length > 1;

    if (phase === "ready" && engineRef.current) {
      setBusy(true);
      setMsgs((m) => [...m, { role: "coach", text: "", ai: true }]);
      try {
        const turns: ChatMsg[] = snapshot
          .slice(1)
          .filter((m) => m.text.trim() && !m.meta)
          .map((m) => ({ role: m.role === "user" ? "user" : "assistant", content: m.text }));
        let acc = "";
        for await (const tok of streamCoachLLM(engineRef.current, buildCoachMessages(t, ctx, turns) as any)) {
          acc += tok;
          setMsgs((m) => {
            const n = m.slice();
            n[n.length - 1] = { role: "coach", text: acc, ai: true };
            return n;
          });
        }
        if (!acc.trim()) throw new Error("empty");
      } catch (e) {
        console.error("[coach] generation failed, falling back", e);
        const ans = coachReply(t, ctx, { followUp });
        setMsgs((m) => {
          const n = m.slice();
          n[n.length - 1] = { role: "coach", text: ans.text };
          return n;
        });
        setChips(ans.chips ?? COACH_STARTER_CHIPS);
      } finally {
        setBusy(false);
      }
      return;
    }

    const ans = coachReply(t, ctx, { followUp });
    setMsgs((m) => [...m, { role: "coach", text: ans.text }]);
    setChips(ans.chips ?? COACH_STARTER_CHIPS);
  }

  function pick(id: string) {
    setSelId(id);
    setCtxChosen(true);
    const e = history.find((x) => x.id === id) ?? null;
    const conf = e
      ? `Tamam — ${entryLabel(e)} analizi üzerinden konuşuyoruz.`
      : "Tamam, belirli bir analize bağlı kalmadan devam edelim.";
    setMsgs((m) => [...m, { role: "coach", text: conf, meta: true }]);
    const q = pendingQ;
    setPendingQ(null);
    if (!q) return;
    // answer the question that was waiting — snapshot excludes that trailing user turn
    let cut = msgs.length;
    for (let i = msgs.length - 1; i >= 0; i--) {
      if (msgs[i].role === "user" && msgs[i].text === q) { cut = i; break; }
    }
    void runAnswer(q, { result: e?.result ?? null, history }, msgs.slice(0, cut));
  }

  function showPicker() {
    setMsgs((m) => [...m, { role: "coach", text: PICK_PROMPT, pick: true, meta: true }]);
  }

  async function ask(text: string) {
    const t = text.trim();
    if (!t || busy) return;
    const snapshot = msgs;
    setInput("");
    setMsgs((m) => [...m, { role: "user", text: t }]);

    const ctx: CoachCtx = { result: selEntry?.result ?? null, history };
    const followUp = snapshot.filter((m) => !m.meta).length > 1;

    if (!isOnTopic(t, ctx, followUp)) {
      setMsgs((m) => [...m, { role: "coach", text: OFFTOPIC_REPLY }]);
      setChips(COACH_STARTER_CHIPS);
      return;
    }

    if (isAnalysisQuestion(t) && !selId && !ctxChosen && history.length > 0) {
      setPendingQ(t);
      setMsgs((m) => [...m, { role: "coach", text: PICK_PROMPT, pick: true, meta: true }]);
      return;
    }

    await runAnswer(t, ctx, snapshot);
  }

  const modeLabel =
    phase === "ready" ? `${LLM_MODELS[loadedKey].sub} · cihazında`
    : phase === "loading" ? `${LLM_MODELS[modelKey].sub} iniyor…`
    : "kural tabanlı · cihazında";
  const offer = LLM_MODELS[modelKey];

  return (
    <div className="card coach">
      <h3>AI Koç <span className="coach-beta">beta · {modeLabel}</span></h3>

      <div className="coach-ctx-line">
        <span>Bağlam: <b>{selEntry ? entryLabel(selEntry) : "genel"}</b></span>
        {history.length > 0 && (
          <button type="button" className="linklike" onClick={showPicker} disabled={busy}>değiştir</button>
        )}
      </div>

      {phase === "idle" && (
        <div className="coach-llm-offer">
          <div className="cllo-body">
            <b>⚡ Gelişmiş yapay zekâ (deneysel)</b>
            <span>Model tamamen cihazında çalışır; indikten sonra internet gerekmez.</span>
            <div className="cllo-tiers" role="radiogroup" aria-label="Model">
              {LLM_MODEL_KEYS.map((k) => (
                <button
                  key={k}
                  className={"cllo-tier" + (modelKey === k ? " on" : "")}
                  aria-pressed={modelKey === k}
                  onClick={() => setModelKey(k)}
                >
                  <b>{LLM_MODELS[k].label}</b>
                  <i>{LLM_MODELS[k].sub}</i>
                  <em>~{(LLM_MODELS[k].downloadMB / 1000).toFixed(LLM_MODELS[k].downloadMB < 1000 ? 2 : 1)} GB</em>
                </button>
              ))}
            </div>
            <span className="cllo-note">{offer.note}</span>
          </div>
          <button className="btn sm" onClick={() => void startLLM(modelKey)}>İndir & etkinleştir</button>
        </div>
      )}
      {phase === "loading" && (
        <div className="coach-llm-load">
          <div className="cll-bar"><span style={{ width: `${progress.pct}%` }} /></div>
          <span className="cll-txt">{progress.pct}% · {progress.text || "hazırlanıyor…"}</span>
        </div>
      )}
      {phase === "error" && (
        <div className="coach-llm-load err">
          Model yüklenemedi (bellek yetmemiş olabilir — daha küçük bir model dene).{" "}
          <button className="linklike" onClick={() => void changeModel()}>model seç</button>
        </div>
      )}

      <div className="coach-log">
        {msgs.map((m, i) => (
          <div key={i} className={"cmsg " + m.role + (m.meta ? " meta" : "")}>
            {m.text === "" ? <span className="ctyping"><i /><i /><i /></span> : <Lines text={m.text} />}
            {m.pick && (
              <div className="coach-pick">
                {history.map((e) => (
                  <button key={e.id} className="chip" onClick={() => pick(e.id)} disabled={busy}>
                    {entryLabel(e)}
                  </button>
                ))}
                <button className="chip ghost" onClick={() => pick("")} disabled={busy}>Analiz olmadan</button>
              </div>
            )}
          </div>
        ))}
        <div ref={endRef} />
      </div>

      <div className="coach-chips">
        {chips.map((c) => (
          <button key={c} className="chip" onClick={() => void ask(c)} disabled={busy}>{c}</button>
        ))}
      </div>

      <form className="coach-input" onSubmit={(e) => { e.preventDefault(); void ask(input); }}>
        <input value={input} onChange={(e) => setInput(e.target.value)}
          placeholder={busy ? "koç yazıyor…" : "Tenisle ilgili bir şey sor…"} disabled={busy} />
        <button className="btn sm" type="submit" disabled={!input.trim() || busy}>Sor</button>
      </form>

      <p className="coach-note">
        {phase === "ready" ? (
          <>Yanıtları {LLM_MODELS[loadedKey].sub} modeli cihazında üretiyor; senin analiz verin + genel tenis bilgisiyle beslenir. Sunucuya hiçbir şey gitmez.{" "}
            <button className="linklike" onClick={() => void changeModel()}>modeli değiştir</button>
            {" · "}
            <button className="linklike" onClick={disableLLM}>kapat</button></>
        ) : phase === "unsupported" ? (
          <>Bu tarayıcı WebGPU desteklemediği için gelişmiş model kullanılamıyor. Kurallı motor — internet, hesap ve LLM gerektirmez.</>
        ) : (
          <>Kurallı motor — internet, hesap ve LLM gerektirmez. Yanıtlar genel tenis bilgisi + senin analiz verinden derlenir.</>
        )}
      </p>
    </div>
  );
}
